### ISSUE TITLE
Example for doing 2-legged OAuth

### ISSUE THREAD

**Issue by antoine1fr** [astrada/gapi-ocaml#14]
Hi,

Is there some examples I can use to 2-legged authentication with gapi-ocaml?

Cheers

**Comment by antoine1fr** [comment]
More precisely (I'm just starting to understand how OAuth works), my server has a refresh token (the one provided by Google's application default credential mechanism), and I want to get a new access token.

**Comment by astrada** [comment]
Sure, you can use [OAuth2.refresh_access_token](https://github.com/astrada/gapi-ocaml/blob/master/src/gapi/gapiOAuth2.mli#L25). Examples: see this [test](https://github.com/astrada/gapi-ocaml/blob/3b7f0c972dab5a556de4400c5fc8fa113cafa53c/src/test/testAuth.ml#L154), or this [file](https://github.com/astrada/gapi-ocaml/blob/master/src/test/refreshOAuth2Token.ml).
