### ISSUE TITLE
Upload latest release to ocamlforge

### ISSUE THREAD

**Issue by bennofs** [astrada/gapi-ocaml#16]
It looks like the latest release on ocamlforge is `0.3.1`. Can you upload the latest one?

**Comment by astrada** [comment]
Well, I didn't update it, because the Forge is going to be [deprecated](http://forge.ocamlcore.org/forum/forum.php?forum_id=958).

**Comment by bennofs** [comment]
@astrada oh, I didn't know about that! Thanks for telling me. I just stumbled over this when trying to update the version of `gapi-ocaml` that the nix package manager provides. So I'll just update it to pull from GitHub instead of the Forge then.
