### ISSUE TITLE
Kubernetes API

### ISSUE THREAD

**Issue by andrenth** [astrada/gapi-ocaml#18]
Hi

Do you think the code generation machinery here could be used to generate a [Kubernetes API](https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json) client?

Cheers.

**Comment by astrada** [comment]
No, sorry. The generator works with the JSON schema of [Google API Discovery Service](https://developers.google.com/discovery/). Doesn't work with swagger/open api.

**Comment by andrenth** [comment]
Oh, I thought the discovery service also used OpenAPI... :(

Thanks!

Em 7 de dez de 2017, à(s) 19:34, Alessandro Strada <notifications@github.com> escreveu:
