### ISSUE TITLE
release 3.9 does not build.

### ISSUE THREAD

**Issue by lemmy04** [astrada/gapi-ocaml#25]
I'm trying to package release 0.3.9 and I'm getting build errors.

`[    8s] + jbuilder build @install
[   12s]       ocamlc src/gapi/.gapi_ocaml.objs/gapiCurl.{cmo,cmt} (exit 2)
[   12s] (cd _build/default && /usr/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w -3-23-27-32-33 -g -bin-annot -I src/gapi/.gapi_ocaml.objs -I src/gapi/.gapi_ocaml.objs/.private -I /usr/lib64/ocaml/biniou -I /usr/lib64/ocaml/bytes -I /usr/lib64/ocaml/cryptokit -I /usr/lib64/ocaml/curl -I /usr/lib64/ocaml/easy-format -I /usr/lib64/ocaml/extlib -I /usr/lib64/ocaml/netstring -I /usr/lib64/ocaml/netsys -I /usr/lib64/ocaml/num -I /usr/lib64/ocaml/threads -I /usr/lib64/ocaml/yojson -intf-suffix .ml -no-alias-deps -opaque -o src/gapi/.gapi_ocaml.objs/gapiCurl.cmo -c -impl src/gapi/gapiCurl.ml)
[   12s] File "src/gapi/gapiCurl.ml", line 287, characters 6-7:
[   12s] Warning 11: this match case is unused.
[   12s] File "src/gapi/gapiCurl.ml", line 1:
[   12s] Error: Some fatal warnings were triggered (1 occurrences)
[   13s]     ocamlopt src/gapi/.gapi_ocaml.objs/gapiCurl.{cmx,o} (exit 2)
[   13s] (cd _build/default && /usr/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w -3-23-27-32-33 -g -I src/gapi/.gapi_ocaml.objs -I src/gapi/.gapi_ocaml.objs/.private -I /usr/lib64/ocaml/biniou -I /usr/lib64/ocaml/bytes -I /usr/lib64/ocaml/cryptokit -I /usr/lib64/ocaml/curl -I /usr/lib64/ocaml/easy-format -I /usr/lib64/ocaml/extlib -I /usr/lib64/ocaml/netstring -I /usr/lib64/ocaml/netsys -I /usr/lib64/ocaml/num -I /usr/lib64/ocaml/threads -I /usr/lib64/ocaml/yojson -intf-suffix .ml -no-alias-deps -opaque -o src/gapi/.gapi_ocaml.objs/gapiCurl.cmx -c -impl src/gapi/gapiCurl.ml)
[   13s] File "src/gapi/gapiCurl.ml", line 287, characters 6-7:
[   13s] Warning 11: this match case is unused.
[   13s] File "src/gapi/gapiCurl.ml", line 1:
[   13s] Error: Some fatal warnings were triggered (1 occurrences)

`

**Comment by astrada** [comment]
You have an old version of `ocurl`. Since version 0.8.0 type `curlDebugType` has 2 more values (https://github.com/ygrek/ocurl/blob/master/curl.mli#L178). If you don't want to upgrade `ocurl`, you should disable warning 11.
