### ISSUE TITLE
Remove Extlib dependency

### ISSUE THREAD

**Issue by shonfeder** [astrada/gapi-ocaml#32]
`extlib` conflicts with `base64`. `base64` would probably make for a nicer decoding experience than `Netencoding`, take one more step towards #10. More compelling: extlib advertises itself as deprecated for new code on its repo, and both `mrmime` and `email_message` depend on `base64`, and either would be useful in conjunction with this library.

**Comment by astrada** [comment]
I would gladly accept a PR.

**Comment by shonfeder** [comment]
If I get a wild hair or any spare time over the next weekend or two, I'd be happy to open one :) I'll update here if I start working on it.
