### ISSUE TITLE
Warning: Unexpected leaf: name=eventType data_type=Scalar in GapiCalendarV3Model.Event.parse

### ISSUE THREAD

**Issue by shonfeder** [astrada/gapi-ocaml#39]
Using the `Calendar` API I've hit this warning:

```
Warning: Unexpected leaf: name=eventType data_type=Scalar in GapiCalendarV3Model.Event.parse
```

Just thought I might report in case it's an indication that an update will be needed at some point.

**Comment by astrada** [comment]
Yes, thanks for reporting it.

**Comment by shonfeder** [comment]
I've just hit another using the discovery API. Recording here lest I forget:

```
Warning: Unexpected leaf: name=flatPath data_type=Scalar in GapiDiscoveryV1Model.RestMethod.parse
```
