### ISSUE TITLE
No support for yojson 2.x

### ISSUE THREAD

**Issue by cedricroijakkers** [astrada/gapi-ocaml#43]
I'm using [google-drive-ocamlfuse](https://github.com/astrada/google-drive-ocamlfuse) which depends on `gapi-ocaml` under Arch Linux (using the AUR package), and since [yojson](https://github.com/ocaml-community/yojson) has been updated to version 2.0.2, `gapi-ocaml` doesn't build anymore since it doesn't support the 2.x API.

For now I've worked around the issue by ignoring updates of the `ocaml-yojson` package in my `/etc/pacman.conf` file, but it would be great if `gapi-ocaml` would support the 2.0 version of `yojson`.

**Comment by astrada** [comment]
As of release 0.4.3 (https://github.com/astrada/gapi-ocaml/releases/tag/v0.4.3), yojson 2.0.0 is supported.

**Comment by cedricroijakkers** [comment]
Thanks, I did not notice you already released a new version. I have [added a comment in the AUR package](https://aur.archlinux.org/packages/gapi-ocaml#comment-906169) that fixes the problem for Arch users. Hopefully, the maintainer will update the package soon. Closing this issue.
